### ISSUE TITLE
Cannot obtain natural images when using mutiple GPUs

### ISSUE THREAD

**Issue by wyf0912** [locuslab/deq-ddim#1]
Thanks for releasing the code of this excellent work.

I meet some problems while sampling from the pre-trained model by running the provided example commands.
The command and its corresponding output is as follows

```shell
python main.py --config cifar10.yml --model Diffusion --exp cifar10-orig-fid --image_folder samples-cifar10-and-t1000-long-new --doc cifar10 --sample --fid --timesteps 1000 --eta 0 --ni --method anderson --use_pretrained
```
<img width="435" alt="image" src="https://user-images.githubusercontent.com/26561397/220547051-d65f18f8-4502-4194-819c-40f895bd67d5.png">

Could you give any advice to solve the problem？

Thank you!

**Comment by wyf0912** [comment]
```shell
python main.py --config church.yml --model Diffusion --exp church-orig-fid --image_folder time-church-and-t25 --doc church --sample --fid --timesteps 25 --eta 0 --ni --method anderson --use_pretrained
```
<img width="411" alt="image" src="https://user-images.githubusercontent.com/26561397/220547422-703d6227-43c6-4ff1-beab-a572367c9c86.png">

**Comment by ashwinipokle** [comment]
Hello, Thank you for your interest in our work. I just cloned a fresh copy of this repository and was able to sample images.

Few examples of generated images for LSUN -Churches generated with the following command:
`
python main.py --config church.yml --model Diffusion --exp church-orig-fid --image_folder time-church-and-t25 --doc church --sample --fid --timesteps 25 --eta 0 --ni --method anderson --use_pretrained`
 
![4](https://user-images.githubusercontent.com/7864463/220695736-33f80be8-870d-40e8-861c-015852aee578.png)

![6](https://user-images.githubusercontent.com/7864463/220695373-f2efe02f-1dec-46c8-9d7f-cc7ee38a0854.png)

Few examples of generated images for CIFAR-10:

`python main.py --config cifar10.yml --model Diffusion --exp cifar10-orig-fid --image_folder samples-cifar10-and-t1000-long-new --doc cifar10 --sample --fid --timesteps 100 --eta 0 --ni --method anderson --use_pretrained --skip_type quad`

![0](https://user-images.githubusercontent.com/7864463/220695574-a9d39e26-03e5-45fc-8aaf-2918f0578859.png)

![4](https://user-images.githubusercontent.com/7864463/220695621-23440755-24cc-415e-9b16-54c465175e07.png)

I am not very sure what could be going wrong if you haven't modified the existing codebase. Could you please verify the following?

1. Are you able to generate samples with simple DDIM sampler ?
The command would be `python main.py --config cifar10.yml --model Diffusion --exp cifar10-orig-fid --image_folder fid-cifar10-seq-t1000 --doc cifar10 --sample --fid --timesteps 1000 --eta 0 --ni --method simple-seq --use_pretrained --skip_type quad`

2. Ensure that you are using  `--use_pretrained` as this would ensure that the checkpoint is getting loaded correctly.
3. Are you using the same config file as in the repository?

Also, if you are using newer versions of PyTorch, you might run into a Runtime Error in Anderson solver as PyTorch has deprecated `torch.solve` in favor of `torch.linalg.solve`.

In that case, the call will look slightly different:

`alpha = torch.linalg.solve(H[:,:n_+1,:n_+1], y[:,:n_+1])[:, 1:n_+1, 0] `

instead of

` alpha = torch.solve(y[:,:n_+1], H[:,:n_+1,:n_+1])[0][:, 1:n_+1, 0] `


I will push this update for newer versions of PyTorch. Let me know if the issue still persists.

**Comment by wyf0912** [comment]
Thanks for your prompt reply!

_I find I can get the correct results when only using one GPU._

While using multiple GPUs, the bug occurs. The generated result when using two GPUs is as follows (it seems better than using 3 GPUs as I previously updated)


![0](https://user-images.githubusercontent.com/26561397/220806032-39680ba7-700f-45ce-b899-65d5b39f3bd8.png)

**Comment by ashwinipokle** [comment]
I am currently unable to replicate this bug. Following are the generated images when I am using multiple GPUs. Is the number of GPUs the only quantity that is changed?

Results for sampling with multiple GPUs (with same commands listed above)- LSUN-Church:

2 GPUs:  8.7 sec / image
![0](https://user-images.githubusercontent.com/7864463/220828719-ae9dc386-d743-4c3e-83ff-88c856cd482f.png)
![2](https://user-images.githubusercontent.com/7864463/220828738-d02c4e3a-f92f-44f6-8f40-d37cb882f1cd.png)

3 GPUs: 7.4 sec / image
![6](https://user-images.githubusercontent.com/7864463/220828771-2ea5b86f-cf5a-467f-a5d3-a4a17f2adc44.png)
![8](https://user-images.githubusercontent.com/7864463/220828780-f9067488-67b5-47f2-ae78-dff5fd9598ac.png)

4 GPUs: 6.9 sec / image
![14](https://user-images.githubusercontent.com/7864463/220828795-191d9c66-219a-4c1d-8e7d-7fa7ff161470.png)
![16](https://user-images.githubusercontent.com/7864463/220828805-a7d569bc-cf9c-421e-b327-98673f444a0a.png)


Results for sampling with multiple GPUs - CIFAR10:

2 GPUs: 5.8 sec / image
![21](https://user-images.githubusercontent.com/7864463/220828940-2d24c374-dcc7-4c9f-b8a8-00fe0192a706.png)
![24](https://user-images.githubusercontent.com/7864463/220828950-d2130045-7a76-4e89-a2ee-4960e1c88068.png)

3 GPUs: 4.3 sec / image
![12](https://user-images.githubusercontent.com/7864463/220828997-95b67d43-0d18-4feb-80fc-9a12819a8abb.png)
![15](https://user-images.githubusercontent.com/7864463/220829010-e5d7cee2-5b18-479b-a447-f279a7d4cc2e.png)

4 GPUs: 3.7 sec / image
![0](https://user-images.githubusercontent.com/7864463/220828910-74c17bfb-81b2-4482-9f4c-0f101a71eb13.png)
![3](https://user-images.githubusercontent.com/7864463/220829036-8aa83da0-23f1-4a62-a0cb-9ec00a2cbf7a.png)

**Comment by wyf0912** [comment]
I will look deeper into the code and maybe I can solve the problem. I will update the info if I make some progress.

Thanks for your reply！

**Comment by ashwinipokle** [comment]
Just in case it is relevant, I tested this on Nvidia GTX 1080 Ti with CUDA version 11.7. Please feel free to email me if the issue persists. Thanks!
